//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIZMETLER
    {
        public HIZMETLER()
        {
            this.RANDEVUDETAYs = new HashSet<RANDEVUDETAY>();
        }
    
        public int ID { get; set; }
        public string ADI { get; set; }
        public decimal FIYAT { get; set; }
        public System.DateTime KAYITTARIHI { get; set; }
        public int FIRMAID { get; set; }
        public bool STATUS { get; set; }
    
        public virtual FIRMALAR FIRMALAR { get; set; }
        public virtual ICollection<RANDEVUDETAY> RANDEVUDETAYs { get; set; }
    }
}
