//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class randevuEntities1 : DbContext
    {
        public randevuEntities1()
            : base("name=randevuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FIRMACALISANLARI> FIRMACALISANLARIs { get; set; }
        public DbSet<FIRMALAR> FIRMALARs { get; set; }
        public DbSet<HIZMETLER> HIZMETLERs { get; set; }
        public DbSet<RANDEVUDETAY> RANDEVUDETAYs { get; set; }
        public DbSet<RANDEVULER> RANDEVULERs { get; set; }
    }
}
