//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandevuSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANDEVULER
    {
        public int ID { get; set; }
        public string ADISOYADI { get; set; }
        public System.DateTime KAYITTARIHI { get; set; }
        public int FIRMAID { get; set; }
        public bool STATUS { get; set; }
        public string TELEFON { get; set; }
        public bool RANDEVUONAY { get; set; }
    
        public virtual FIRMALAR FIRMALAR { get; set; }
    }
}
